# Sparse CNN Model Configuration
model:
  name: "sparsecnn"
  type: "instance_segmentation"
  
  # Voxelization
  voxel_size: 0.02
  max_num_points: 250000
  
  # Backbone configuration
  backbone:
    in_channels: 4  # xyz + feature
    base_channels: 32
    
    blocks: [
      # [channels, num_layers, stride]
      [32, 2, 1],
      [64, 3, 2],
      [128, 4, 2],
      [256, 6, 2],
      [512, 3, 2]
    ]
    
    norm_type: "batch"
    activation: "relu"
    dropout: 0.2
    
  # Decoder configuration
  decoder:
    fpn_channels: 256
    num_fpn_layers: 4
    
    head_channels: [256, 128, 64]
    num_classes: 18  # ScanNet classes
    
  # Instance head
  instance_head:
    feature_dim: 64
    embedding_dim: 32
    hidden_dims: [128, 128]
    max_instances: 64

# Loss configuration
loss:
  semantic_weight: 1.0
  center_weight: 1.0
  offset_weight: 1.0
  instance_weight: 1.0
  
  center_loss:
    type: "l2"
    sigma: 1.0
    
  offset_loss:
    type: "l1"
    norm_factor: 1.0

# Optimization
optimizer:
  type: "adam"
  learning_rate: 0.001
  weight_decay: 0.0001
  
  scheduler:
    type: "one_cycle"
    max_lr: 0.001
    epochs: 200
    steps_per_epoch: 1000
    pct_start: 0.4

# Training
training:
  epochs: 200
  batch_size: 4
  num_workers: 4
  log_interval: 10
  save_interval: 5
  
  early_stopping:
    patience: 15
    min_delta: 0.001
    
  mixed_precision: true
  gradient_clipping: 10.0