# Dataset configuration
dataset:
  num_points: 8192  
  num_classes: 21  
  use_color: true   
  normalize_color: true 

# Preprocessing configuration
preprocessing:
  min_points_per_instance: 100 
  max_instances_per_scene: 100   
  voxel_size: 0.02 

# Data augmentation
augmentation:
  enabled: true
  random_rotation: true
  random_scale: [0.8, 1.2]
  random_flip: true
  jitter_strength: 0.01
  random_dropout: 0.2