# Model configuration
model:
  embedding_dim: 64  # Dimension of instance embeddings
  feature_dim: 6    # 3 for position + 3 for color

# Training configuration
training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.00001
  num_workers: 4
  early_stopping_patience: 15
  visualization_frequency: 50
  save_frequency: 5
  gradient_clip: 1.0

# Loss configuration
loss:
  type: 'instance_seg'
  weights:
    clustering: 1.0
    center: 0.5
    boundary: 0.3
    lovasz: 0.01
    smoothness: 0.08
  params:
    delta_v: 0.1
    delta_d: 0.5
    gamma: 0.0001
    focal_alpha: 0.25
    focal_gamma: 2.0

# Data configuration
data:
  num_points: 8192
  use_color: true
  normalize_color: true
  augmentation:
    enabled: true
    random_rotation: true
    random_scale: [0.8, 1.2]
    random_flip: true
    jitter_strength: 0.01
    random_dropout: 0.2

# Optimizer configuration
optimizer:
  type: 'adam'
  beta1: 0.9
  beta2: 0.999

# Learning rate scheduler configuration
scheduler:
  enabled: true
  type: 'cosine'  # Type of scheduler
  T_max: 100      # Number of epochs
  eta_min: 0.00001  # Minimum learning rate
  patience: 15      # For early stopping
  factor: 0.5     # Learning rate reduction factor

# Logging configuration
logging:
  log_frequency: 10
  use_wandb: true
  project_name: "scannet-instance-seg"